name: Nightfall
favicon: null
layout_spectrum: 0.6008330185431987
typography_spectrum: 0.9999008076265454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21575604565441608
  lightness: 0.5692526779603213
  saturation: 0.8627960192970932
  rhythmicContrast: 0.9746272775810212
purpose: []
